# System Configuration
system:
  name: "AI File System"
  version: "1.0.0"
  environment: "development"
  
  # Performance settings
  max_workers: 4
  batch_size: 10
  timeout_seconds: 300
  
  # Resource management
  max_memory_mb: 4096
  max_file_size_mb: 50
  
  # Security
  allow_network_operations: true
  enable_backups: true
  backup_retention_days: 30
  
  # Logging
  log_level: "INFO"
  enable_file_logging: true
  enable_console_logging: true
  
  # AI Services
  default_ai_provider: "ollama"
  fallback_providers: ["openai", "anthropic"]
  
  # File Processing
  supported_formats:
    documents: [".pdf", ".docx", ".doc", ".txt", ".rtf", ".odt"]
    images: [".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".webp"]
    code: [".py", ".js", ".java", ".cpp", ".html", ".css", ".php", ".rb"]
    data: [".csv", ".json", ".xml", ".yaml", ".yml"]
  
  default_encoding: "utf-8"
  backup_file_extension: ".backup"